### ISSUE TITLE
Some inconsistencies in naming and data types

### ISSUE THREAD

**Issue by mkaze** [JetBrains/KotlinDL#106]
The inconsistencies are as follows:

**ModelLoader.kt**

- The name of some of the layer creator functions follows the pattern `create[layer_name]Layer` while others don't use that "Layer" at the end. [suggestion for fixining this: refactor and always use "Layer" at the end for these functions.]
- The return type of some of the layer creator functions has been set as `Layer` while others use the type of the specific layer (e.g. Dense, or Flatten layer). [suggestion for fixing this: always use `Layer` as the return type of these functions.]

**ModelSaver.kt**

- Same as the first point for "ModelLoader.kt".

**Numerical types**

- We are using both `Long` and `Int` in an interchangeable way. For example, `AvgPool2D` and `MaxPool2D` are using the type `IntArray` for their public properties like `poolSize` (which is then converted to `Long` in `forward` method), while most of the other layers stick to `Long`. [suggestion for fixing this: not sure... on one hand it seems the underlying Java API expects `Long` most of the time, but on the other hand using `Long` in places where `Int` already works seems to be a bit redundant.]

**Comment by zaleslaw** [comment]
Totally agree with you for naming and data types in both, ModelSaver and ModelLoader.
Are you going to create a PR for that, or could I rename it?

Regarding numerical types: this problem about Long/Int, arrays in strides/kernels to pass it directly to underlying TF Java API
I created a discussion [here ](https://github.com/JetBrains/KotlinDL/discussions/110). Please join and share your approach there.

**Comment by mkaze** [comment]
> Are you going to create a PR for that, or could I rename it?

Sure, I'll create a PR for that.

**Comment by zaleslaw** [comment]
Great, hope to merge it quickly
