### ISSUE TITLE
Add GlobalMaxPool2D layer

### ISSUE THREAD

**Issue by mkaze** [JetBrains/KotlinDL#116]
Currently, the support for `GlobalMaxPool2D` is missing and it would be great if we could add support for this layer as well. The desired PR addressing this issue should include:

- Implementation of layer class named as `GlobalMaxPool2D` (you can take inspiration from implementation of [`GlobalMaxPool1D`][1] as reference)
- Documentation of layer.
- Test cases
- Support for export of layer to JSON (see [ModelSaver.kt][2])
- Support for import of layer from JSON (see [ModelLoader.kt][3])

Also, if needed, you can take a look at [Keras documentation for this layer](https://keras.io/api/layers/pooling_layers/global_max_pooling2d/). **NOTE**: for the moment, there is no need to add support for "data format" (i.e. channels last vs. channels first) in your PR; you can simply assume the channels are always in the last dimension.

[1]: https://github.com/JetBrains/KotlinDL/blob/master/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/core/layer/pooling/GlobalMaxPool1D.kt

[2]: https://github.com/JetBrains/KotlinDL/blob/master/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/ModelSaver.kt

[3]: https://github.com/JetBrains/KotlinDL/blob/master/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/ModelLoader.kt

**Comment by zaleslaw** [comment]
So, are you going to create PR by yourself or we will mark it with the "good first issue"?

**Comment by mkaze** [comment]
> So, are you going to create PR by yourself or we will mark it with the "good first issue"?

@zaleslaw, :smiley: All right, I'll take it.
