### ISSUE TITLE
Missed documentation in Conv classes hierarchy

### ISSUE THREAD

**Issue by zaleslaw** [JetBrains/KotlinDL#118]
After merging I recognized that the KDocs for the Conv class hierarchy are missed

Please add KDocs for all classes, methods, and fields in the following classes

- [ ] AbstractConv (class, properties, methods)
- [ ] Conv1D (methods)
- [ ] Conv2D (methods)
- [ ] Conv3D (methods)
- [ ] DepthwiseConv2D (methods)

I suppose that enough to define good KDoc for the parent (protected) method of property, the documentation is inherited by child methods

**Comment by zaleslaw** [comment]
@avan1235 will you take this ticket?

**Comment by avan1235** [comment]
Yes, of course, as it is my fault that I didn't provide them with the code
