### ISSUE TITLE
Add model name to the summary method

### ISSUE THREAD

**Issue by zaleslaw** [JetBrains/KotlinDL#120]
Our models could have names, but the current version of _summary_ method (for both, Sequential and Functional models) doesn't support model name displaying.

The PR should include:
- [x] model name support for both, Functional and Sequential model
- [x] the missed model name case is handled correctly 
- [x] SequentialCompilationTest.summary should be updated for validation model name
- [ ] Test for the Functional model _summary_ is added (you could use here model like ToyResNet)
- [ ] (Optional) Refactoring of both summary methods (in Functional and Sequential models)

**Comment by dosier** [comment]
I could do this one :)

**Comment by dosier** [comment]
@zaleslaw to what extend do both summary methods have to be refactored? E.g. does the method signature have to change at all?

**Comment by zaleslaw** [comment]
I've changed the ticket description regarding refactoring: the refactoring will be optional, the API is not under stability guarantees and could be changed.

The refactoring is just an idea, looks like it could be refactoring, but it's your choice as a contributor: propose the refactoring (with minor changes in the signature that doesn't affect all examples and tests) because there is some copy-paste there and common logic, but PR could be merged and without refactoring

**Comment by dosier** [comment]
@zaleslaw do the above commits cover the first 3 points in this issue sufficiently? Or is this not what you meant. And I can look into the refactoring yes.

**Comment by zaleslaw** [comment]
I've added the [Contributing Guidelines](https://github.com/JetBrains/KotlinDL/blob/master/CONTRIBUTING.md). Please check this.

**Comment by zaleslaw** [comment]
You solution is simple and solves the problem

**Comment by dosier** [comment]
Maybe the refactor part and writing a test is better suited as a part of #135 than this issue @zaleslaw ?

**Comment by zaleslaw** [comment]
I suggest do things step by step, the final form of model summary is unclear and there are a few moments related to logging, jupyter integration and so on.

I suggest to finish this ticket and if the form of summary will be changed, we will not ignore the modelname
