### ISSUE TITLE
Add Cropping1D and Cropping3D layers

### ISSUE THREAD

**Issue by zaleslaw** [JetBrains/KotlinDL#121]
Currently, the support for `Cropping1D` and `Cropping3D`  are missed, and it would be great if we could add support for these layers. The desired PR addressing this issue should include:

- [ ]  Implementation of layer class named as `Cropping1D` (you can take inspiration from the implementation of [`Cropping2D`][1] as reference)
- [ ]   Implementation of layer class named as `Cropping3D` (you can take inspiration from the implementation of [`Cropping2D`][1] as reference)
- [ ] Common hierarchy of all Cropping layers with abstract cropping class with the common functionality
- [ ]  Documentation of layer and all non-private methods
- [ ]   JUnit tests in `api ` module
- [ ]   Support for export of layer to JSON (see [ModelSaver.kt][2])
- [ ]   Support for import of layer from JSON (see [ModelLoader.kt][3])

Also, if needed, you can take a look at Keras documentation for [`Cropping1D`](https://keras.io/api/layers/reshaping_layers/cropping1d/) and [`Cropping3D`](https://keras.io/api/layers/reshaping_layers/cropping3d/). 

**NOTE**: for the moment, there is no need to add support for "data format" (i.e., channels last vs. channels first) in your PR; you can assume the channels are always in the last dimension.

[1]: https://github.com/JetBrains/KotlinDL/blob/master/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/core/layer/reshaping/Cropping2D.kt

[2]: https://github.com/JetBrains/KotlinDL/blob/master/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/ModelSaver.kt

[3]: https://github.com/JetBrains/KotlinDL/blob/master/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/ModelLoader.kt

P.S. If you want to take this ticket, please leave the comment below
P.P.S Read the [Contributing Guidelines](https://github.com/JetBrains/KotlinDL/blob/master/CONTRIBUTING.md).

**Comment by mkaze** [comment]
I'll take this one.
