### ISSUE TITLE
Add RepeatVector layer

### ISSUE THREAD

**Issue by zaleslaw** [JetBrains/KotlinDL#123]
Currently, the support for `RepeatVector ` is missed, and it would be great to add support for these layers. The desired PR addressing this issue should include:

- [ ]  Implementation of layer class named as `RepeatVector ` (you can take inspiration from the implementation of [`Reshape`][1] as reference)
- [ ]  Documentation of layer and all non-private methods
- [ ]   JUnit tests in `api ` module
- [ ]   Support for export of layer to JSON (see [ModelSaver.kt][2])
- [ ]   Support for import of layer from JSON (see [ModelLoader.kt][3])

Also, if needed, you can take a look at Keras documentation for [`RepeatVector `](https://keras.io/api/layers/reshaping_layers/repeat_vector/)

**NOTE**: for the moment, there is no need to add support for "data format" (i.e., channels last vs. channels first) in your PR; you can assume the channels are always in the last dimension.

[1]: https://github.com/JetBrains/KotlinDL/blob/master/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/core/layer/reshaping/Reshape.kt

[2]: https://github.com/JetBrains/KotlinDL/blob/master/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/ModelSaver.kt

[3]: https://github.com/JetBrains/KotlinDL/blob/master/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/ModelLoader.kt

P.S. If you want to take this ticket, please leave the comment below
P.P.S Read the [Contributing Guidelines](https://github.com/JetBrains/KotlinDL/blob/master/CONTRIBUTING.md).

**Comment by dosier** [comment]
I could do this one :)

**Comment by dosier** [comment]
Hey @zaleslaw I am a bit lost on how best to write tests for RepeatVector class. Should I dig into the unit tests of Keras and convert them to Kotlin, or come up with tests myself?

**Comment by zaleslaw** [comment]
If the logic is simple, like in max pooling 2d layer, you could make it as you wish, if it includes complex calculations you could use some numerical data from keras, but you don't need make full copy of its tests, 1 or 2 for forward and main exceptions or cornerstones. Or you could use keras to pass input and get output of the tested layer.

**Comment by dosier** [comment]
@zaleslaw alright. I added a simple test in https://github.com/dosier/KotlinDL/commit/bf61c5db2a2308d6b7ea547a7b44ac7fb1ba34c4. This is probably not enough though. What do u mean by cornerstones?

**Comment by zaleslaw** [comment]
hmm, maybe test for the negative number n=-10, for example, to get an IllegalArgumentException (you could use `require` in Kotlin for this)
