### ISSUE TITLE
Change the TrainableModel::summary API to return `ModelSummary`

### ISSUE THREAD

**Issue by avan1235** [JetBrains/KotlinDL#135]
In current implementation the [TrainableModel::summary](https://github.com/JetBrains/KotlinDL/blob/2e529a89058617e22fd81e783c7b1af07c1cbfa9/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/core/TrainableModel.kt#L317) return the list with the descriptions for the following layers.

This information is readable but doesn't allow for easy transformation of model summary gathered data as it is give as raw String. Additionally, the implementation classes log the provided layers description in more readable way, but it is only printed on stdio and not available at least as pretty formatted string that could bu printed later. The problem is more annoying in jupyter notebooks where we don't have an access to stdio and so the logged pretty summary is not visible.

I would propose creating some simple `ModelSummary` data class that would be responsible for holding the model summary data and would have some good implementation of `toString()` method that could be easily printed. It would allow for creating custom printing methods for `ModelSummary` as well as good keeping of model summary data as a single object instead of `List<String>`

**Comment by zaleslaw** [comment]
Hi, @knok16. Give me a few days to think about it; I'll return to you in a couple of days.

**Comment by zaleslaw** [comment]
Thanks for lighting the problem @avan1235. I totally agree about that the existing solution is not good for notebooks.
So great to have a few data classes like @knok16 proposed.

I suppose the proposed solution should contain the following things:

- [ ] data classes for Model and layer summary
- [ ] printSummary and logSummary functions (logging could print on a console too)
- [ ] tests for Sequential, Functional models and a few popular layers like Conv2D, ZeroPadding2D 
- [ ] refactoring for all examples which contain it.summary() to it.logSummary() for consistency.
- [ ] 1 executed notebook with the built artifact from the proposed PR to estimate how pretty it is

**Comment by knok16** [comment]
Can I take it?

**Comment by zaleslaw** [comment]
@knok16 Sure, it's yours

**Comment by knok16** [comment]
changes for pp 1-3 https://github.com/JetBrains/KotlinDL/pull/216
will do p.4 in separate PR, to not clutter this one

**Comment by zaleslaw** [comment]
Mostly closed in the #216 
I will release an artifact, load it to the Maven Central and make a double check on the Datalore and Jupyter notebooks

**Comment by zaleslaw** [comment]
I've checked the 0.3.0-alpha-4 artifact, print summary works as expected and this issue has been fixed.
