### ISSUE TITLE
Can we add our author tag in KDoc when we make a new class?

### ISSUE THREAD

**Issue by dosier** [JetBrains/KotlinDL#137]
So say I write an unique class or do significant work in someone else's class, can I add my author tag to it, e.g.:
```
/**
 * @author Stan van der Bend
 */
 ```

**Comment by dosier** [comment]
Now to think of it, sorry I should probably not have turned this into an issue but rather communicate through the discussion board. I'll leave it here for now.

**Comment by zaleslaw** [comment]
So, this is an ancient and outdated practice from ancient times (like Java 1.0), then developers did not use Git or SVN.
In many cases, it means not the real author who created the code but the maintainer or contact person for this class or functionality.

So, your authorship is written to the Git and also your effort is displayed [here ](https://github.com/JetBrains/KotlinDL/graphs/contributors)

Also, you could found a very good SO [discussion ](https://stackoverflow.com/questions/17269843/javadoc-author-tag-good-practices)about it and news about removing these tags from Apache Software and [Gradle OSS projects](https://github.com/gradle/gradle/commit/a1b9612fa06f90f20b115cede557e22287501034)

**Comment by dosier** [comment]
@zaleslaw thanks explanation, and the SO discussion was an interesting read!
