### ISSUE TITLE
Add Permute layer

### ISSUE THREAD

**Issue by mkaze** [JetBrains/KotlinDL#142]
Currently, the support for Permute layer is missing and it would be great if we could add support for this layer as well. The desired PR addressing this issue should include:

- Implementation of layer class named as Permute (hint: you can use `tf.linalg.transpose(...)` for forward pass of this layer).
- Documentation of layer.
- Test cases
- Support for export of layer to JSON (see [ModelSaver.kt][1])
- Support for import of layer from JSON (see [ModelLoader.kt][2])

Also, if needed, you can take a look at [Keras documentation for this layer](https://keras.io/api/layers/reshaping_layers/permute/). 

[1]: https://github.com/JetBrains/KotlinDL/blob/master/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/ModelSaver.kt

[2]: https://github.com/JetBrains/KotlinDL/blob/master/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/ModelLoader.kt

**Comment by therealansh** [comment]
I'll like to work on this one.

**Comment by therealansh** [comment]
Hey @mkaze the Permute layer implementation in keras uses `perm` which is a tuple. While in the `tf.linalg.transpose(...)` perm needs to be of `Operand<U extends Number>` . I dont think we can typecast a tuple(IntArray) into Number(Int)?

**Comment by mkaze** [comment]
@therealansh As far as I understand, the all `Operand` values resolve in a `Tensor` and therefore the `U` in `Operand<U>` refers to the underlying datatype of each single element of `Tensor` (e.g. `Float`, `Int`, etc.).
So you can simply put the permutation in an `IntArray` and then use `tf.constant`, like `tf.constant(permArray)`, to create an instance of `Constant<Int>` (which is a basically a subclass of `Operand`) and then pass it to `transpose` function.

**Comment by zaleslaw** [comment]
Agree with @mkaze tf.constant will work for the array in this case, look at [this ](https://github.com/JetBrains/KotlinDL/blob/master/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/core/layer/reshaping/Flatten.kt#L29) in Flatten
