### ISSUE TITLE
Add UpSampling layers

### ISSUE THREAD

**Issue by mkaze** [JetBrains/KotlinDL#143]
Currently, the support for UpSampling layers is missing and it would be great if we could add support for these layers as well. The desired PR addressing this issue should include:

- [ ]  Implementation of layers classes named as `UpSampling1D`, `UpSampling2D` and `UpSampling3D`.
- [ ]  Common hierarchy of all UpSampling layers with abstract class with the common functionality
- [ ]  Documentation of layer and all non-private methods
- [ ]   JUnit tests in `api ` module
- [ ]  Support for export of layers to JSON (see [ModelSaver.kt][1])
- [ ]  Support for import of layers from JSON (see [ModelLoader.kt][2])

Also, if needed, you can take a look at Keras documentation for these layers: [UpSampling1D](https://keras.io/api/layers/reshaping_layers/up_sampling1d), [UpSamplling2D](https://keras.io/api/layers/reshaping_layers/up_sampling2d) and [UpSampling3D](https://keras.io/api/layers/reshaping_layers/up_sampling3d). 

**NOTE:** for the moment, there is no need to add support for "data format" (i.e. channels last vs. channels first) in your PR; you can simply assume the channels are always in the last dimension.

[1]: https://github.com/JetBrains/KotlinDL/blob/master/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/ModelSaver.kt

[2]: https://github.com/JetBrains/KotlinDL/blob/master/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/ModelLoader.kt

**Comment by mkaze** [comment]
I'll take this one.

**Comment by zaleslaw** [comment]
It's a very interesting bunch of layers, @mkaze good luck with that, it includes a lot of functionality in the Keras, we should try to avoid repeating all of it, ignoring things not related to the current state of the KotlinDL
