### ISSUE TITLE
SequentialInferenceTest takes too long (15+ minutes on my machine)

### ISSUE THREAD

**Issue by kokorins** [JetBrains/KotlinDL#148]
it's worth simplify or add some description how to run just unit tests and separate long running "integration" tests in a separate gradle command.

**Comment by zaleslaw** [comment]
Hi, @kokorins 

The running of the JUnit test only is possible via `api:test` like it described in the [Contribution Guidelines](https://github.com/JetBrains/KotlinDL/issues/145) file

**Comment by dosier** [comment]
How about that long-running tests are always performed before a PR is merged into the main branch, but are optional for making a PR and contributing to that PR? That way short tests can still be performed during development whilst not hindering devs from working. Ideally these final tests could be performed on a central server 😉 @zaleslaw.
I am not sure if something like this could be automated and how hard it would be to do so.

**Comment by zaleslaw** [comment]
The time of tests is reduced in many places due to changing the main constants, but integration tests are kept as a part of testing
