### ISSUE TITLE
Load trainability status of layers when importing them from JSON configuration

### ISSUE THREAD

**Issue by mkaze** [JetBrains/KotlinDL#153]
Similar to #107, the trainability status of a layer is not taken into account when importing it from JSON configuration, e.g. if a layer is freezed in the saved JSON configuration it might be loaded as trainable (depending on the default value of `isTrainable` property for that layer).

To fix this, either each of the layer creator functions in `ModelLoader.kt` should be modified to set the `isTrainable` property of the created layer with value of `config.trainable`; or alternatively, this could be done in a single place like [`convertToLayer`][1] function for all layers. Further, one should take into account [this issue](https://github.com/JetBrains/KotlinDL/issues/152#issuecomment-866977400) when implementing a fix.

[1]: https://github.com/JetBrains/KotlinDL/blob/2a5d580920a80e94f706562413f00ecf6c20dce9/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/ModelLoader.kt#L112

**Comment by zaleslaw** [comment]
I agree that it could be implemented now, but in reality, we need to add more check/IllegalStateExceptions if the layer implementing the NoGradients layer has an `isTrainable == true ` status.

The idea is the following: layers with NoGradient marker interface should have this status as `false`.

**Comment by dosier** [comment]
I can do this one

**Comment by dosier** [comment]
How about something like this:
```kotlin
        LAYER_SOFTMAX -> createSoftmaxLayer(kerasLayer.config!!, kerasLayer.config.name!!)
        else -> throw IllegalStateException("${kerasLayer.class_name} is not supported yet!")
    }.apply {
        isTrainable = if (kerasLayer.config.trainable == true) {
            require(this is NoGradients) {
                "layer config contains `trainable` as `true` but layer is NoGradients which can not be trainable."
            }
            true
        } else
            false
    }
 ```
in
https://github.com/JetBrains/KotlinDL/blob/2a5d580920a80e94f706562413f00ecf6c20dce9/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/ModelLoader.kt#L112


And then I remove all the manual assignments of `isTrainable` for the `NoGradients` implementations.

**Comment by dosier** [comment]
> I agree that it could be implemented now, but in reality, we need to add more check/IllegalStateExceptions if the layer implementing the NoGradients layer has an `isTrainable == true ` status.
> 
> The idea is the following: layers with NoGradient marker interface should have this status as `false`.

Should these checks u mention for NoGradients layers be applied only to these, or to other layers as well. Because some layers do set `isTrainable` to `false` but do not implement NoGradients. So should these other layers implement NoGradients, or should we make another interface that every non trainable layers extends?

**Comment by dosier** [comment]
Yo @zaleslaw or @mkaze what do ya think about something like this:
https://github.com/dosier/KotlinDL/commit/8e414181137945557d3a8802985869a93e1f15e8

I don't really like how the default value is `true` but can't nicely change it to something like:
```kotlin
    public var isTrainable: Boolean = this is NoGradients
```
without leaking `this`  in the constructor.

I see three options:
- keep it like in the commit I made 
- leak `this` in constructor of Layer class
- add `isTrainable` as constructor param

But maybe one of your has a better idea (or anyone else!!)
