### ISSUE TITLE
Confusing logs when using Keras model

### ISSUE THREAD

**Issue by rcd27** [JetBrains/KotlinDL#155]
I've loaded a trained model with its weights and config file, like shown in https://github.com/JetBrains/KotlinDL/blob/master/docs/importing_keras_model.md
There are some logs with `INFO` tag, which look a bit confusing for person, who is not yet comfortable with Keras/Tensorflow:
![image](https://user-images.githubusercontent.com/20042955/123809549-5dad6380-d8fa-11eb-8e49-637e46d3437d.png)

Maybe change that kind of logs to `DEBUG`?

**Comment by dosier** [comment]
I agree, then maybe the number of parameters loaded could be added to the `no weights loading for ...` prints (or as separate prints). Might be good to move this to the [discussions](https://github.com/JetBrains/KotlinDL/discussions) section.
