### ISSUE TITLE
Incorrect temporary folder for the cat-vs-dogs dataset

### ISSUE THREAD

**Issue by zaleslaw** [JetBrains/KotlinDL#161]
WE have incorrect paths in the [embeddedDatasets.kt](https://github.com/JetBrains/KotlinDL/blob/master/api/src/main/kotlin/org/jetbrains/kotlinx/dl/dataset/embeddedDatasets.kt#L276): the temporary data.zip is loaded to the `datasets/catdogs/data.zip` instead of `datasets/dogs-vs-cats/data.zip` 

1. Fix the issue
2. Refactor String constants moving common parts to one common constant
3. Check that the loading is correct with one of [these examples](https://github.com/JetBrains/KotlinDL/tree/master/examples/src/main/kotlin/examples/cnn/dogscats) in the `cache `directory

**Comment by funkstermonster** [comment]
Hi! I started working on it. Can I have access this repo to assign it for me?

**Comment by funkstermonster** [comment]
I commited the solution. Would be grateful, if I could push them to a separate branch and open a pr.

**Comment by mkaze** [comment]
@funkstermonster Thank your for your interest and contribution. You should first fork this repository and push your commits to your own fork on Github. Then you will be able to make a Pull Request (PR) to merge your changes to this repository. Please see this guide for more info: https://github.com/firstcontributions/first-contributions#first-contributions

Also, please review the contributing guidelines of KotlinDL [here](https://github.com/JetBrains/KotlinDL/blob/master/CONTRIBUTING.md).

**Comment by funkstermonster** [comment]
I might have troubles linking the issue the and PR together, since the cog icon is missing for me.

**Comment by mkaze** [comment]
> I might have troubles linking the issue and the PR together, since the cog icon is missing for me.

@funkstermonster You just need to use one of the special keywords followed by the issue number in the PR description to link them together. See [this guide](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for some help and examples.

**Comment by funkstermonster** [comment]
Thank you for your help. Linked the issue.

**Comment by zaleslaw** [comment]
Thanks for the help for newcomers, @mkaze ! You are the best!
Dear @funkstermonster I'll do the review during the next 2 days and answer you in the linked PR
Welcome to the KotlinDL
