### ISSUE TITLE
CI failed on M1

### ISSUE THREAD

**Issue by zaleslaw** [JetBrains/KotlinDL#164]
I used the MacOS machine with the M1 to run the tests and examples.
The following error was obtained:

```
java.lang.UnsatisfiedLinkError: Cannot find TensorFlow native library for OS: darwin, architecture: aarch64. See https://github.com/tensorflow/tensorflow/tree/master/tensorflow/java/README.md for possible solutions (such as building the library from source). Additional information on attempts to find the native library can be obtained by adding org.tensorflow.NativeLibrary.DEBUG=1 to the system properties of the JVM.
  at org.tensorflow.NativeLibrary.load(NativeLibrary.java:77)
  at org.tensorflow.TensorFlow.init(TensorFlow.java:67)

```

**Comment by chaloxavi** [comment]
Hi, I have the same error, could you tell me how to fix it?

**Comment by dkandalov** [comment]
I guess the answer is that KotlinDL currently doesn't support M1. It would be good to make this a bit more explicit.

From https://github.com/Kotlin/kotlindl/issues/172#issuecomment-900338401
> The KotlinDL internally uses TF 1.15 runtime, which means you can use it only with the previous Mac without M1.
