### ISSUE TITLE
Add Mish activation function

### ISSUE THREAD

**Issue by zaleslaw** [JetBrains/KotlinDL#168]
The Mish activation function is missed in KotlinDL.

Read more about [Mish: A Self Regularized Non-Monotonic Neural Activation Function](https://arxiv.org/abs/1908.08681)

The desired PR addressing this issue should include:

- [ ]  Implementation of activation class named as `MishActivation` (you can take inspiration from the implementation of [`HardSigmoid`][1]  as reference) added to the [`Activations.kt`][2] file
- [ ]  Documentation of activation function
- [ ]  JUnit tests in `api ` module
- [ ]  Support for export of activation function to JSON (see [ModelSaver.kt][3])
- [ ]  Support for import of activation function from JSON (see [ModelLoader.kt][4])

[1]: https://github.com/JetBrains/KotlinDL/blob/master/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/core/activation/Activations.kt#L344

[2]:
https://github.com/JetBrains/KotlinDL/blob/master/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/core/activation/Activations.kt

[3]: https://github.com/JetBrains/KotlinDL/blob/master/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/ModelSaver.kt

[4]: https://github.com/JetBrains/KotlinDL/blob/master/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/ModelLoader.kt

P.S. If you want to take this ticket, please leave the comment below
P.P.S Read the [Contributing Guidelines](https://github.com/JetBrains/KotlinDL/blob/master/CONTRIBUTING.md).

The reference implementation could be taken from [tensorflow-addons](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/activations/mish.py)

**Comment by zaleslaw** [comment]
Hi, @digantamisra98! Please leave a comment here to assign this ticket to you.
As I understand, you are the author of the Mish paper, a really great paper and results!

**Comment by digantamisra98** [comment]
@zaleslaw Yes, I am taking this up and will be happy to add others over the weekend (hopefully). Thank you for your compliment and willingness to add it in the library :)

**Comment by zaleslaw** [comment]
@digantamisra98 I hope that KotlinDL could be more faster and open to DL innovations, will wait review request from you

**Comment by digantamisra98** [comment]
The PR is ready for review (I don't know if I can like request a review on the PR itself unless I'm a collaborator with write access).
