### ISSUE TITLE
Add TimeStopping callback

### ISSUE THREAD

**Issue by zaleslaw** [JetBrains/KotlinDL#174]
It's an exciting idea to limit the training via the maximum limit of training time.

The idea is implemented in [tf-addons](https://www.tensorflow.org/addons/api_docs/python/tfa/callbacks/TimeStopping) and could be adopted in KotlinDL

The desired PR addressing this issue should include:

- [ ]  Implementation of TimeStopping callback
- [ ]  Documentation 
- [ ]  Integration test with callback (see [LeNetWithEarlyStoppingCallback][1] )

[1]: https://github.com/JetBrains/KotlinDL/blob/master/examples/src/main/kotlin/examples/cnn/mnist/advanced/LeNetWithEarlyStoppingCallback.kt

P.S. If you want to take this ticket, please leave the comment below
P.P.S Read the [Contributing Guidelines](https://github.com/JetBrains/KotlinDL/blob/master/CONTRIBUTING.md).

The reference implementation could be taken from [tensorflow-addons](https://github.com/tensorflow/addons/blob/v0.13.0/tensorflow_addons/callbacks/time_stopping.py)

**Comment by mkaze** [comment]
I'll take this one.

**Comment by zaleslaw** [comment]
Great @mkaze, assigned on you, if you have any ideas about callbacks feel free to share it here on make a topic in discussions
