### ISSUE TITLE
Add Leaky ReLU activation function

### ISSUE THREAD

**Issue by Rishit-dagli** [JetBrains/KotlinDL#192]
It seems the Leaky ReLU activation function is missed in KotlinDL. I would love to contribute this if it sounds good.

**Comment by mkaze** [comment]
@Rishit-dagli Actually, it has been already implemented as an activation layer; see [here](https://github.com/JetBrains/KotlinDL/blob/master/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/core/layer/activation/LeakyReLU.kt).

**Comment by Rishit-dagli** [comment]
Ah, got it, I was looking for an activation function. Thanks!
