### ISSUE TITLE
Metrics logs with `fit` are visible with verbose=0

### ISSUE THREAD

**Issue by michalharakal** [JetBrains/KotlinDL#20]
I am not sure if it is a really an issue, but it has confused me a little bit. Calling `fit` on model for training with `verbose=false` produces logs with metrics. As far as I understood, INFO log level was set properly on beginning, but for metrics is logger called as `debug`. 

It is a different to behaviour with Keras, at least with 2.x  If I wanted more granular informations in loggs regarding training, I would implemented a callback for that, so I believe true/false for complete silence is fine.

**Comment by zaleslaw** [comment]
@michalharakal Agree, that logging should more clear and be correctly separated for levels. Do you think that with verbose = false it should be really silent model?

**Comment by michalharakal** [comment]
@zaleslaw I see two main possibilities. 

1. verbose = 0 => completely silent. In that case you can have your own logs with a few lines via `callback`
2. you change API and introduce enum for more granular logs (I thing in Keras they have verbose being Int)

I would vote for  *verbose = 0 => completely silent* with power of callback for custommization and a lot of default information with *verbose = 1*. So we provide by default many usefull intofmations and if you want to tweek them, you switch logging off and write your own logger via callback, which can be e.g. network call for updating microservice with jobs monitoring .....

**Comment by zaleslaw** [comment]
@michalharakal We decided to move logging in this framework from Keras - pythonic side to the common JVM practice with log4j logging and verbose levels via configuration.

Silent mode could be set up via OFF mode in log4j2.xml config (it will be added to the examples).

Also, I'm going to add an example with custom logging via custom callback, thanks for the idea.
