### ISSUE TITLE
Data and Models separation from core API library

### ISSUE THREAD

**Issue by michalharakal** [JetBrains/KotlinDL#21]
Current API jar contains resources with data sets and serialized models, which are used in examples. It makes jar file huge and brings a lot of questions regardings maintainance, data sources legal licencing etc.

### Supported use cases:

- ML "hello world" with MNIST data set should a few lines both in regular java application and so in Jupyter
- API deliverable itself is slick jar to be usable in small docker containers (even serverless lambdas ???)

### Ideas:
- plugable data set loader as a separate library (support for various sources http, git .... ??? )
- gradle plugin ( not usefull with jupyter ... )

**Comment by zaleslaw** [comment]
Thanks @michalharakal it's a good feature request and described use-case. There is no the best solution here, but maybe the additional "small" jar provided as dependency could be helpful here. Something like "slim-api" dependency.

**Comment by michalharakal** [comment]
@zaleslaw I would maybe workout more on the idea of data/model provider. We could do the similar approach as we know from java loggers. Its just an interface, in a default case with NoOp implementation. Linking another jar with the real implementation (e.g. getting the data set, or model from git, or just binary download) or I could even have dowloader.jar my fancy `Enterprisy` downloading models from on premise secure S3 buket....  
This solution support your idea of having slim-api ....

**Comment by lamba92** [comment]
> We could do the similar approach as we know from java loggers. Its just an interface, in a default case with NoOp implementation.

I would not recommend that approach. It is very confusing for newcomers since it's implicit! Also, when and if going multiplatform, it would be a new problem!

**Comment by zaleslaw** [comment]
Dear @lamba92 could you please explain why it would be a new problem if going multiplatform?

**Comment by zaleslaw** [comment]
@michalharakal Totally agree about datasets, need to think about dataset hosting and possible loading via HTTP client or something else

**Comment by zaleslaw** [comment]
It was fixed in https://github.com/JetBrains/KotlinDL/pull/43
