### ISSUE TITLE
Exception in combination with Log4J

### ISSUE THREAD

**Issue by quickstep24** [JetBrains/KotlinDL#22]
My project uses Log4J in combination with kotlin-logging:
```
dependencies {
   ...
   implementation("io.github.microutils", "kotlin-logging-jvm", "2.0.3")
   implementation("org.apache.logging.log4j", "log4j-slf4j-impl", "2.13.0")
}
```
This library is obviously hard-coded to expect logback loggers:
```
Exception in thread "main" java.lang.ClassCastException: org.apache.logging.slf4j.Log4jLogger cannot be cast to ch.qos.logback.classic.Logger
	at org.jetbrains.kotlinx.dl.api.inference.InferenceModel.setLevel(InferenceModel.kt:64)
	at org.jetbrains.kotlinx.dl.api.core.Sequential.internalFit(Sequential.kt:364)
	at org.jetbrains.kotlinx.dl.api.core.Sequential.fit(Sequential.kt:313)
```

**Comment by quickstep24** [comment]
A workaround is to set `verbose` to true.
Btw: why is `verbose` a parameter? Shouldn't this be handled through logger configuration?

**Comment by zaleslaw** [comment]
Thanks for feedback, @quickstep24 looks like here are in battle two approaches: Keras API consistency, which uses verbose as a method parameter and log configuration traditions from JVM world. I suppose we should be closer to JVM.

**Comment by zaleslaw** [comment]
Dear @quickstep24 . I removed all logback usages in the code (all of them related to the logging level set up in code) and make a step to be more JVM library. But logback dependency is in api module. What do you think? Is it enough for your request? If you will have logback dependecy and log4j dependency on classpath, you could use the [following solution](http://www.slf4j.org/codes.html#multiple_bindings ), isn't it?
