### ISSUE TITLE
Dense layer without bias (useBias = false) throws `lateinit property bias has not been initialized`

### ISSUE THREAD

**Issue by knok16** [JetBrains/KotlinDL#223]
If `useBias = false` used for `Dense` layer
https://github.com/JetBrains/KotlinDL/blob/master/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/core/layer/core/Dense.kt#L58
`createDenseVariables` will not fill `bias` field
https://github.com/JetBrains/KotlinDL/blob/master/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/core/layer/core/Dense.kt#L95
https://github.com/JetBrains/KotlinDL/blob/master/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/core/layer/core/Dense.kt#L66
and later `forward` will throw `lateinit property bias has not been initialized` in this line
https://github.com/JetBrains/KotlinDL/blob/master/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/core/layer/core/Dense.kt#L111

Also `paramCount` in case of `Dense(useBias = false)` calculated incorrectly (in includes parameters related to bias later, despite of its absence)
https://github.com/JetBrains/KotlinDL/blob/master/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/core/layer/core/Dense.kt#L126

**Comment by zaleslaw** [comment]
Hi, @knok16, are you going to fix it by yourself, or I do that?

**Comment by knok16** [comment]
Yes, please, assign it to me, I'll try to fix it this week

**Comment by knok16** [comment]
https://github.com/JetBrains/KotlinDL/pull/232
