### ISSUE TITLE
reshapeFunction not initialized after model load

### ISSUE THREAD

**Issue by quickstep24** [JetBrains/KotlinDL#24]
I store a model with 
```
val model = Sequential.of(
            Input(...),
            Dense(...),
            Dropout(...),
            Dense(...),
            Dense(1)
        )
model.compile(...)
model.fit(...)
model.save(dir, TF_GRAPH_CUSTOM_VARIABLES, true, FAIL_IF_EXISTS)
```
then I reload and use it with
```
val model = InferenceModel.load(dir)
model.predictSoftly(...)
```
But I get an exception:
```
Exception in thread "main" kotlin.UninitializedPropertyAccessException: lateinit property reshapeFunction has not been initialized
	at org.jetbrains.kotlinx.dl.api.inference.InferenceModel.predictSoftly(InferenceModel.kt:128)
	at org.jetbrains.kotlinx.dl.api.inference.InferenceModel.predictSoftly$default(InferenceModel.kt:127)
```
My fault or is this a bug?
Not sure about `SavingFormat` because two entries have same description.

**Comment by zaleslaw** [comment]
Hi, @quickstep24 Thanks for the question.
1. You used the correct format
2. Reshape function is not serialized and should be write manually, look to this [example](https://github.com/JetBrains/KotlinDL/blob/master/examples/src/main/kotlin/examples/inference/production/fashionmnist/LeNetFashionMnistExportImport.kt)
3. In the method '''predictSoftly'' was an incorrect ''require'', I fixed it in the commit, closing this issue.
4. Correct message and exception will be availalbe in 0.1.1 release
