### ISSUE TITLE
Onnx models are not available (onnx examples)

### ISSUE THREAD

**Issue by kokorins** [JetBrains/KotlinDL#244]
```
Server returned HTTP response code: 403 for URL: https://kotlindl.s3.amazonaws.com/models/onnx/objectdetection/yolov4.onnx
```

**Comment by zaleslaw** [comment]
Hi @kokorins could I ask you: how do you get this error message? There is no official example with the YOLOv4 model.

All models are public on S3 (I made a double-check for that) but I got sometimes the same error message on macOS then I tried to download model from S3 firstly (I don't know why)

**Comment by kokorins** [comment]
in onnx example replace sff with yolov4

**Comment by zaleslaw** [comment]
Could you open this URL in browser (it should suggest to load model)? What OS and browser do you use?

**Comment by zaleslaw** [comment]
@kokorins we made a double-check on our side from a few machines with a different OS, looks like your request to S3 is forbidden for some reason, so let's try to find the reason for it.

**Comment by kokorins** [comment]
Thanks, it's working now!

**Comment by zaleslaw** [comment]
Thanks for the signal @kokorins the problem is that I do nothing and it worries me.
