### ISSUE TITLE
BatchNorm layer do not initialize `fanIn`/`fanOut` parameters

### ISSUE THREAD

**Issue by knok16** [JetBrains/KotlinDL#245]
`BatchNorm::build` do not initialize `fanIn`/`fanOut` [parameters](https://github.com/JetBrains/KotlinDL/blob/master/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/core/layer/Layer.kt#L38) of `Layer` before calling `Layer::addWeight` [here](https://github.com/JetBrains/KotlinDL/blob/master/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/core/layer/normalization/BatchNorm.kt#L79). As I understand it can lead to an incorrect initialization for some initializers, but I'm not sure, since validation for such case is [commented](https://github.com/JetBrains/KotlinDL/blob/master/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/core/layer/Layer.kt#L126). 

Is it the expected behavior of `BatchNorm` layer?

**Comment by zaleslaw** [comment]
It's closed in #324
