### ISSUE TITLE
java.io.EOFException: Unexpected end of ZLIB input stream

### ISSUE THREAD

**Issue by Reqeique** [JetBrains/KotlinDL#291]
so while i was leading DL in kotlin ,
 
I got an error saying `java.io.EOFException: Unexpected end of ZLIB input stream`  For instance the 
error was pointing at `fashionMnist()` function so I tried cloning the function on my local code , which ends up spotting at `extractImage`(https://github.com/JetBrains/KotlinDL/blob/master/api/src/main/kotlin/org/jetbrains/kotlinx/dl/dataset/handler/MnistUtil.kt line 34)  At this point I tried everything but no luck !
full code
```
fun main(){
    Sequential.of(
        Input(28,28,1),
        Flatten(),
        Dense(300),
        Dense(100),
        Dense(10)
    ).use {
        it.compile(
            optimizer = Adam(),
            loss = Losses.SOFT_MAX_CROSS_ENTROPY_WITH_LOGITS,
            metric = Metrics.ACCURACY
        )
        it.printSummary()
        val (train, test) = fashionMnist()
        it.fit(
            dataset = train,
            epochs = 10,
            batchSize = 100
        )
        val accuracy = it.evaluate(dataset = test, batchSize = 100).metrics[Metrics.ACCURACY]
        println("Accuracy: $accuracy")
        it.save(File("model/my_model"), writingMode = WritingMode.OVERRIDE)
        println(File("model/my_model").absolutePath)
    }
}
```
env
KOTLIN_V = "1.5.30"
JAVA_V = "15.0.2"
KOTLIN_DL_V = "0.3.0"

**Comment by zaleslaw** [comment]
Could you please try to clean up the cache directory with the downloaded datasets and check permissions for the writing/reading to this directory?

**Comment by Reqeique** [comment]
after removing the cache dir it made it work ,thanks!
