### ISSUE TITLE
`Functional.of` silently skips layers without inbound layers.

### ISSUE THREAD

**Issue by juliabeliaeva** [JetBrains/KotlinDL#314]
Consider the following code:
```kotlin
    val model = Functional.of(
        Input(128, 128, name = "input"),
        Conv2D(name = "conv")
    )
    println(model.layers.size)
```
This code outputs "1" and the created model has a single input layer, however this was probably not the authors intention. The problem is with the `Functional.Companion#topologicalSort` method which does not support disconnected graphs and just silently skips layers which are not reachable from the input. Instead an exception should be thrown, or at least an error printed in this case.

**Comment by zaleslaw** [comment]
Thank you for this issue, agree about the warning or better with exception here
