### ISSUE TITLE
Code duplication in `WeightLoader`

### ISSUE THREAD

**Issue by juliabeliaeva** [JetBrains/KotlinDL#325]
`WeightLoader` has a number of methods to load all or a subset of layers in variety of ways, but essentially all of them are performing the same task:
1. Check that model can load weights.
2. Load weights for a subset of layers, and initialise weights for other layers.
3. Mark model as initialised.

Refactoring is needed to unify these methods.

**Comment by zaleslaw** [comment]
Refactor TIME!!!
