### ISSUE TITLE
`GraphTrainableModel#internalPredict` works only with one-dimensional predictions

### ISSUE THREAD

**Issue by juliabeliaeva** [JetBrains/KotlinDL#327]
It should be possible to make predictions of multiple-dimensions, for example, images, like in the [Autoencoder example](https://github.com/JetBrains/KotlinDL/pull/315#issuecomment-1001430860). However, the linked example fails at https://github.com/JetBrains/KotlinDL/blob/11d4eb175323b61d2e709d4133cbbde49c033746/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/core/GraphTrainableModel.kt#L698 as `predictionsTensor` has differrent dimentionality from `dst`.

**Comment by juliabeliaeva** [comment]
The simplest fix would be to just linearize `predictionsTensor` to a `FloatArray`. This will allow to keep the current api and to make the `Autoencoder` example work (we already can show `FloatArray` images in the `ImagePanel`).
If this is ok, I'll send a pr.

**Comment by zaleslaw** [comment]
I see this problem, please send a PR to fix that, @juliabeliaeva
