### ISSUE TITLE
[Feature Request] Clone model

### ISSUE THREAD

**Issue by technight** [JetBrains/KotlinDL#40]
As far as I can tell the API does not allow you to directly clone a model? Specifically I want an identical model with all the same layers, weights, optimizer settings etc.

The only current solution I can find is to save and load the model from disk, but it would be nice to have the ability to copy without spending time on all the IO required for saving and loading from disk.

**Comment by zaleslaw** [comment]
@technight great idea, do you have any ideas about possible or required API?

**Comment by technight** [comment]
I think something simple like .clone() or .copy() on InferenceModel would be sufficent for my needs
