### ISSUE TITLE
Klaxon dependency

### ISSUE THREAD

**Issue by MKhalusova** [JetBrains/KotlinDL#5]
Setting up a dependency to org.jetbrains.kotlin.kotlin-dl:api:0.0.5 does not seem to be enough. 
I got: 
Could not find com.beust:klaxon:5.0.1.
Required by:
    project : > org.jetbrains.kotlin.kotlin-dl:api:0.0.5

Adding explicit dependency on klaxon helps. However, it's not ideal.

**Comment by zaleslaw** [comment]
Great @MKhalusova will fix during bug-fix phase!

**Comment by zaleslaw** [comment]
@MKhalusova could you say, is it fixed now?

**Comment by MKhalusova** [comment]
@zaleslaw yes, it is. Thank you!

**Comment by Blacktoviche** [comment]
I'm having the same issue. `Could not find artifact com.beust:klaxon:pom:5.0.1 in mavenCentral (https://repo1.maven.org/maven2/)`

here is my maven 

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>consoleApp</artifactId>
    <groupId>dl</groupId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>consoleApp</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <kotlin.code.style>official</kotlin.code.style>
        <kotlin.compiler.jvmTarget>1.8</kotlin.compiler.jvmTarget>
    </properties>

    <repositories>
        <repository>
            <id>mavenCentral</id>
            <url>https://repo1.maven.org/maven2/</url>
        </repository>
        <repository>
            <id>jcenter</id>
            <name>jcenter</name>
            <url>https://kotlin.bintray.com/kotlin-datascience</url>
        </repository>
    </repositories>

    <build>
        <sourceDirectory>src/main/kotlin</sourceDirectory>
        <testSourceDirectory>src/test/kotlin</testSourceDirectory>
        <plugins>
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
                <version>1.4.21</version>
                <executions>
                    <execution>
                        <id>compile</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>test-compile</id>
                        <phase>test-compile</phase>
                        <goals>
                            <goal>test-compile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.2</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.22.2</version>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>1.6.0</version>
                <configuration>
                    <mainClass>MainKt</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-test-junit</artifactId>
            <version>1.4.21</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib-jdk8</artifactId>
            <version>1.4.21</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin-deeplearning</groupId>
            <artifactId>api</artifactId>
            <version>0.1.0</version>
            <type>pom</type>
        </dependency>
    </dependencies>

</project>`

things are going great with gradle but I prefer maven and love to start such a project using it

**Comment by zaleslaw** [comment]
I will test with maven and suggest a fix, thanks for your question

пт, 18 дек. 2020 г., 14:36 Malek Tarboush <notifications@github.com>:
