### ISSUE TITLE
Add Identity intializer

### ISSUE THREAD

**Issue by zaleslaw** [JetBrains/KotlinDL#50]
We are missing some initializers to fully support the export of models from Keras. One of them is the Identity initializer.

Add an initializer class, write documentation for it, write a test for it, try, if possible, create a small trainable network with it (in your own GitHub) and attach a link.

Also, support for export and import of initializer in JSON format should be added (see [ModelLoader.kt ](https://github.com/JetBrains/KotlinDL/blob/master/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/ModelLoader.kt) and [ModelSaver.kt](https://github.com/JetBrains/KotlinDL/blob/master/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/ModelSaver.kt))

A detailed description of the initializer can be found [here](https://keras.io/api/layers/initializers/)

**Comment by hbrammer** [comment]
Hi there 👋🏻 
I'm new to the party and would love to help. 
Created a first draft of this in #73 

I will hopefully complete this in the next couple of days.
