### ISSUE TITLE
Add PReLU layer

### ISSUE THREAD

**Issue by zaleslaw** [JetBrains/KotlinDL#54]
We are missing some activation layers to support the export of models from Keras fully. One of them is the PReLU layer.

Add an activation layer class, write documentation for it, write a test for it, try, if possible, create a small trainable network with it (in your own GitHub) and attach a link here in the comments.

The layer should be placed [here](https://github.com/JetBrains/KotlinDL/tree/master/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/core/layer/activation)

As a reference implementation, the [ReLU activation layer](https://github.com/JetBrains/KotlinDL/blob/master/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/core/layer/activation/ReLU.kt) could be used, but feel free to improve it!

Also, support for export and import of activation layer in JSON format should be added (see [ModelLoader.kt ](https://github.com/JetBrains/KotlinDL/blob/master/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/ModelLoader.kt) and [ModelSaver.kt](https://github.com/JetBrains/KotlinDL/blob/master/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/ModelSaver.kt))

A detailed description of the activation layer can be found [here](https://keras.io/api/layers/activation_layers/prelu/)

**Comment by mkaze** [comment]
I'll take this one and work on it.

**Comment by therealansh** [comment]
I think PReLU requires Regularization of weights, to calculate the alpha. And the regularizations is yet to be implemented (#83 ) i guess?

**Comment by mkaze** [comment]
@therealansh A regularizer is *not necessarily* used; actually, you can optionally provide a regularizer as well, but in the default case it works without any regularization or constraint on the weights. Nonetheless, it should be added in any case; so I have left a TODO comment for that in my implementation.

**Comment by zaleslaw** [comment]
Good comment, @therealansh, about regularizers, but now it's not supported yet and will be an issue later (I'll suggest adding an issue about that).

So, agree with @mkaze we could work with a simple PReLU version now (adding a TODO with a link on the newly created issue and #83 could be a good solution)
