### ISSUE TITLE
Create Website with API Documentation from KDoc

### ISSUE THREAD

**Issue by e5l** [JetBrains/KotlinDL#71]
It would be really great to have the website with a search ability from all documentation we already have in KDoc. Here is the link to get started: https://kotlin.github.io/dokka/1.4.32/user_guide/gradle/usage/

**Comment by zaleslaw** [comment]
Great, thanks for the advice, we started Dokka integration, but it was not finished yet.

**Comment by zaleslaw** [comment]
The documentation for the 0.2 version was added here https://jetbrains.github.io/KotlinDL/index.html
