### ISSUE TITLE
Add model export for a few layers, missed in ModelSaver.kt

### ISSUE THREAD

**Issue by zaleslaw** [JetBrains/KotlinDL#87]
Each layer should be exported in JSON, Keras compatible format
The following layers are missed in ModelSaver.kt

1. Concatenate
2. ZeroPadding2D
3. DepthwiseConv2D
4. SeparableConv2D

NOTE: some another layers' export, like Activation or merge layers like Subtract and so on are parts of other PRs now

**Comment by mkaze** [comment]
I'll take this one.
