### ISSUE TITLE
"Pool" or "Pooling" ?!

### ISSUE THREAD

**Issue by mkaze** [JetBrains/KotlinDL#94]
Currently, we are using a mix of both "Pool" and "Pooling" words in naming the variables, functions, classes and the files, as well as in constant string values. I think this might bring confusion and inconsistency. It would be a good idea to choose only one of these and use it all over the codebase. Of course, we can choose the other one only as required (e.g. for compatibility with Keras when loading models).

For comparison, this was also used to be the case in Keras/TF (and indeed [it creates confusion](https://stackoverflow.com/q/63006575/2099607) as some users thought "pool" and "pooling" are different!); however, to mitigate it to some degree TF developers now use "pool", and the "pooling" would be considered as an alias of "pool" (even in documentation links); although, with the exception of "average pooling" which still uses "pooling" (probably because they have used "average" instead of "avg" for clarity and therefore in this case decided to chose the longer version, i.e. "pooling" instead of "pool", for consistency).

Personally, I suggest to always use "MaxPool" and "AvgPool" in naming everything, from variables to files to values of string constants. And only use "Pooling" as necessary (e.g. for compatibility reasons).

**Comment by mkaze** [comment]
An update on this about compatibility: I just checked this and Keras is using "pooling" (instead of "pool") in the output of `layer.get_config()` and `model.get_config()` (for both fields of `name` and `class_name`) which in turn is used by `model.to_json()` to export model config as JSON. This is true for all layers.

**Comment by zaleslaw** [comment]
Great, I dislike the long AveragePooling and prefer AvgPool too, so it could be renamed in the same manner, then all tickets related to pooling for 1d/3d will be merged.
We use Conv instead Convolution, Pool instead Pooling, Max instead Maximum.
PyTorch has the same short names: https://pytorch.org/docs/stable/generated/torch.nn.MaxPool2d.html

Regarding Keras compatibility: we will keep it on configuration saving level and could add notes about that in comments about layer serialization.

**Comment by zaleslaw** [comment]
I suppose that you could use short versions in tickets assigned to you, final renaming could be performed later

**Comment by mkaze** [comment]
> I suppose that you could use short versions in tickets assigned to you, final renaming could be performed later

Yeah, I have already used the short version in all the related PRs.
